Update package imports and module names

diff --git a/DEBIAN/prerm b/DEBIAN/prerm
--- a/DEBIAN/prerm
+++ b/DEBIAN/prerm
@@ -1,40 +1,36 @@
 #!/bin/sh
 
-
 before_remove() {
     :
 
-debsystemctl=$(command -v deb-systemd-invoke || echo systemctl)
-$debsystemctl stop weeve-agent >/dev/null || true
+    debsystemctl=$(command -v deb-systemd-invoke || echo systemctl)
+    $debsystemctl stop beeta-agent >/dev/null || true
 
-LINE=$(systemctl cat weeve-agent.service | grep "ExecStart")
-COMMAND="${LINE#ExecStart=} --delete"
+    LINE=$(systemctl cat beeta-agent.service | grep "ExecStart")
+    COMMAND="${LINE#ExecStart=} --delete"
 
-systemctl disable weeve-agent >/dev/null || true
-systemctl --system daemon-reload >/dev/null || true
+    systemctl disable beeta-agent >/dev/null || true
+    systemctl --system daemon-reload >/dev/null || true
 
-# run the agent again with --delete flag to clean up
-cd /var/lib/weeve-agent && eval "$COMMAND" 2>&1 && cd -
+    # run the agent again with --delete flag to clean up
+    cd /var/lib/beeta-agent && eval "$COMMAND" 2>&1 && cd -
 }
 
 dummy() {
     :
 }
 
-if [ "${1}" = "remove" -a -z "${2}" ]
-then
+if [ "${1}" = "remove" -a -z "${2}" ]; then
     # "before remove" goes here
     before_remove
-elif [ "${1}" = "upgrade" ]
-then
+elif [ "${1}" = "upgrade" ]; then
     # Executed before the old version is removed
     # upon upgrade.
     # We should generally not do anything here. The newly installed package
     # should do the upgrade, not the uninstalled one, since it can't anticipate
     # what new things it will have to do to upgrade for the new version.
     dummy
-elif echo "${1}" | grep -E -q "(fail|abort)"
-then
+elif echo "${1}" | grep -E -q "(fail|abort)"; then
     echo "Failed to install before the pre-removal script was run." >&2
     exit 1
 fi
